"""Initial_migration_ORM_models

Revision ID: e534771c93df
Revises: 
Create Date: 2026-10-08 12:47:42.928907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'e534771c93df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Cases_case_code'), table_name='legacy_Cases')
    op.drop_index(op.f('ix_Cases_status'), table_name='legacy_Cases')
    op.drop_index(op.f('ix_Cases_student_identifier'), table_name='legacy_Cases')
    op.drop_table('legacy_Cases')
    op.drop_index(op.f('ix_EvidenceComparisons_case_id'), table_name='EvidenceComparisons')
    op.drop_table('EvidenceComparisons')
    op.drop_index(op.f('ix_Policies_code'), table_name='Policies')
    op.drop_table('Policies')
    op.drop_index(op.f('ix_VerificationResults_run_id'), table_name='VerificationResults')
    op.drop_table('VerificationResults')
    op.drop_index(op.f('ix_HumanReviews_case_id'), table_name='HumanReviews')
    op.drop_table('HumanReviews')
    op.drop_index(op.f('ix_AuditLogs_case_id'), table_name='AuditLogs')
    op.drop_table('AuditLogs')
    op.drop_index(op.f('ix_Escalations_case_id'), table_name='Escalations')
    op.drop_table('Escalations')
    op.drop_index(op.f('ix_CaseMessages_case_id'), table_name='CaseMessages')
    op.drop_table('CaseMessages')
    op.drop_index(op.f('ix_PolicyRules_policy_id'), table_name='PolicyRules')
    op.drop_index(op.f('ix_PolicyRules_rule_code'), table_name='PolicyRules')
    op.drop_table('PolicyRules')
    op.drop_index(op.f('ix_VerificationRuns_run_code'), table_name='VerificationRuns')
    op.drop_table('VerificationRuns')
    op.drop_index(op.f('ix_Evidence_case_id'), table_name='Evidence')
    op.drop_index(op.f('ix_Evidence_sha256_hash'), table_name='Evidence')
    op.drop_table('Evidence')
    op.drop_index(op.f('ix_Departments_code'), table_name='Departments')
    op.drop_table('Departments')
    op.drop_index(op.f('ix_EvidenceExtractions_evidence_id'), table_name='EvidenceExtractions')
    op.drop_table('EvidenceExtractions')
    op.drop_index(op.f('ix_CaseDecisions_case_id'), table_name='CaseDecisions')
    op.drop_table('CaseDecisions')
    op.create_index(op.f('ix_audits_caseId'), 'audits', ['caseId'], unique=False)
    op.alter_column('cases', 'priority',
               existing_type=sa.NVARCHAR(length=50, collation='Vietnamese_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("('MEDIUM')"))
    op.create_index(op.f('ix_cases_studentId'), 'cases', ['studentId'], unique=False)
    op.create_index(op.f('ix_comments_caseId'), 'comments', ['caseId'], unique=False)
    op.create_foreign_key(None, 'comments', 'users', ['authorId'], ['id'])
    op.create_index(op.f('ix_evidence_uploads_ownerId'), 'evidence_uploads', ['ownerId'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.NVARCHAR(length=50, collation='Vietnamese_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("('INFO')"))
    op.alter_column('notifications', 'isRead',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
    op.create_index(op.f('ix_notifications_userId'), 'notifications', ['userId'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_userId'), 'refresh_tokens', ['userId'], unique=False)
    op.alter_column('users', 'twoFactorEnabled',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
    op.alter_column('users', 'mustChangePassword',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'mustChangePassword',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
    op.alter_column('users', 'twoFactorEnabled',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
    op.drop_index(op.f('ix_refresh_tokens_userId'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_notifications_userId'), table_name='notifications')
    op.alter_column('notifications', 'isRead',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
    op.alter_column('notifications', 'type',
               existing_type=sa.NVARCHAR(length=50, collation='Vietnamese_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("('INFO')"))
    op.drop_index(op.f('ix_evidence_uploads_ownerId'), table_name='evidence_uploads')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_caseId'), table_name='comments')
    op.drop_index(op.f('ix_cases_studentId'), table_name='cases')
    op.alter_column('cases', 'priority',
               existing_type=sa.NVARCHAR(length=50, collation='Vietnamese_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("('MEDIUM')"))
    op.drop_index(op.f('ix_audits_caseId'), table_name='audits')
    op.create_table('CaseDecisions',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('decision_type', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('policy_reference', sa.NVARCHAR(length=200, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('evidence_summary', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['legacy_Cases.id'], name=op.f('FK__CaseDecis__case___5EBF139D')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__CaseDeci__3213E83F49B9EB3C'))
    )
    op.create_index(op.f('ix_CaseDecisions_case_id'), 'CaseDecisions', ['case_id'], unique=False)
    op.create_table('EvidenceExtractions',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('evidence_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.NVARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('structured_data_json', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('extraction_summary', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('has_uncertain_fields', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('uncertain_fields_json', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['Evidence.id'], name=op.f('FK__EvidenceE__evide__59063A47')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Evidence__3213E83F32F6AC7A'))
    )
    op.create_index(op.f('ix_EvidenceExtractions_evidence_id'), 'EvidenceExtractions', ['evidence_id'], unique=False)
    op.create_table('Departments',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('name', sa.NVARCHAR(length=200, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Departme__3213E83F4A79B841'))
    )
    op.create_index(op.f('ix_Departments_code'), 'Departments', ['code'], unique=False)
    op.create_table('Evidence',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('evidence_type', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('original_file_name', sa.NVARCHAR(length=255, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('stored_file_name', sa.NVARCHAR(length=255, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sha256_hash', sa.VARCHAR(length=64, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.NVARCHAR(length=500, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('source_description', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('analysis_status', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['legacy_Cases.id'], name=op.f('FK__Evidence__case_i__5629CD9C')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Evidence__3213E83FDD06CB36'))
    )
    op.create_index(op.f('ix_Evidence_sha256_hash'), 'Evidence', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_Evidence_case_id'), 'Evidence', ['case_id'], unique=False)
    op.create_table('VerificationRuns',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('run_code', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('total_cases', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passed_cases', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_cases', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('completed_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Verifica__3213E83FA1BD91FF'))
    )
    op.create_index(op.f('ix_VerificationRuns_run_code'), 'VerificationRuns', ['run_code'], unique=False)
    op.create_table('PolicyRules',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('rule_code', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('name', sa.NVARCHAR(length=200, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('condition_type', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('condition_value', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['Policies.id'], name=op.f('FK__PolicyRul__polic__6E01572D')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__PolicyRu__3213E83F07B269B9'))
    )
    op.create_index(op.f('ix_PolicyRules_rule_code'), 'PolicyRules', ['rule_code'], unique=False)
    op.create_index(op.f('ix_PolicyRules_policy_id'), 'PolicyRules', ['policy_id'], unique=False)
    op.create_table('CaseMessages',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('sender_type', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('sender_name', sa.NVARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('message', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['legacy_Cases.id'], name=op.f('FK__CaseMessa__case___534D60F1')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__CaseMess__3213E83F021557EF'))
    )
    op.create_index(op.f('ix_CaseMessages_case_id'), 'CaseMessages', ['case_id'], unique=False)
    op.create_table('Escalations',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('escalation_type', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('target_department_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('target_role', sa.NVARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('question', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('evidence_summary', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['legacy_Cases.id'], name=op.f('FK__Escalatio__case___619B8048')),
    sa.ForeignKeyConstraint(['target_department_id'], ['Departments.id'], name=op.f('FK__Escalatio__targe__628FA481')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Escalati__3213E83F347AE603'))
    )
    op.create_index(op.f('ix_Escalations_case_id'), 'Escalations', ['case_id'], unique=False)
    op.create_table('AuditLogs',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('actor_type', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('actor_name', sa.NVARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('action', sa.NVARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('input_snapshot', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('evidence_ids', sa.VARCHAR(length=500, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('reason', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('policy_reference', sa.NVARCHAR(length=200, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('result_snapshot', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['legacy_Cases.id'], name=op.f('FK__AuditLogs__case___68487DD7')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__AuditLog__3213E83FCFBCF868'))
    )
    op.create_index(op.f('ix_AuditLogs_case_id'), 'AuditLogs', ['case_id'], unique=False)
    op.create_table('HumanReviews',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('reviewer_name', sa.NVARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('reviewer_role', sa.NVARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('decision', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['legacy_Cases.id'], name=op.f('FK__HumanRevi__case___656C112C')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__HumanRev__3213E83FFB63E883'))
    )
    op.create_index(op.f('ix_HumanReviews_case_id'), 'HumanReviews', ['case_id'], unique=False)
    op.create_table('VerificationResults',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('case_identifier', sa.VARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('case_title', sa.NVARCHAR(length=255, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('expected_decision', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('actual_decision', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('expected_escalation', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('actual_escalation', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('is_passed', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('details_json', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['VerificationRuns.id'], name=op.f('FK__Verificat__run_i__73BA3083')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Verifica__3213E83F12C8B258'))
    )
    op.create_index(op.f('ix_VerificationResults_run_id'), 'VerificationResults', ['run_id'], unique=False)
    op.create_table('Policies',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('name', sa.NVARCHAR(length=200, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=20, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Policies__3213E83F89CC4451'))
    )
    op.create_index(op.f('ix_Policies_code'), 'Policies', ['code'], unique=False)
    op.create_table('EvidenceComparisons',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('left_evidence_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('right_evidence_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('field_name', sa.VARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('left_value', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('right_value', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('comparison_status', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['legacy_Cases.id'], name=op.f('FK__EvidenceC__case___5BE2A6F2')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Evidence__3213E83F9BE158B3'))
    )
    op.create_index(op.f('ix_EvidenceComparisons_case_id'), 'EvidenceComparisons', ['case_id'], unique=False)
    op.create_table('legacy_Cases',
    sa.Column('id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('case_code', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('title', sa.NVARCHAR(length=255, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('student_identifier', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('case_type', sa.VARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('current_department_id', sa.VARCHAR(length=36, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('sis_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('sis_status', sa.VARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_department_id'], ['Departments.id'], name=op.f('FK__Cases__current_d__5070F446')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Cases__3213E83F25597C5E'))
    )
    op.create_index(op.f('ix_Cases_student_identifier'), 'legacy_Cases', ['student_identifier'], unique=False)
    op.create_index(op.f('ix_Cases_status'), 'legacy_Cases', ['status'], unique=False)
    op.create_index(op.f('ix_Cases_case_code'), 'legacy_Cases', ['case_code'], unique=False)
    # ### end Alembic commands ###
