from enum import Enum

class CaseStatus(str, Enum):
    NEW = "NEW"
    EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
    ANALYZING = "ANALYZING"
    WAITING_FOR_INFORMATION = "WAITING_FOR_INFORMATION"
    AUTO_RESOLVED = "AUTO_RESOLVED"
    ESCALATED = "ESCALATED"
    WAITING_FOR_HUMAN = "WAITING_FOR_HUMAN"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    STOPPED = "STOPPED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class EscalationType(str, Enum):
    FACT_UNKNOWN = "FACT_UNKNOWN"
    POLICY_OUT_OF_SCOPE = "POLICY_OUT_OF_SCOPE"
    AUTHORITY_REQUIRED = "AUTHORITY_REQUIRED"
    DATA_CONFLICT = "DATA_CONFLICT"
    OWNERSHIP_UNCLEAR = "OWNERSHIP_UNCLEAR"

class DecisionType(str, Enum):
    AUTO_RESOLVE = "AUTO_RESOLVE"
    REQUEST_INFORMATION = "REQUEST_INFORMATION"
    ESCALATE = "ESCALATE"
    REJECT = "REJECT"
    NO_DECISION = "NO_DECISION"

class ComparisonStatus(str, Enum):
    MATCH = "MATCH"
    MISMATCH = "MISMATCH"
    UNKNOWN = "UNKNOWN"
    NOT_COMPARABLE = "NOT_COMPARABLE"

class HumanReviewAction(str, Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    OVERRIDE = "OVERRIDE"
    REQUEST_INFORMATION = "REQUEST_INFORMATION"
    STOP = "STOP"
    RESUME = "RESUME"

class ActorType(str, Enum):
    STUDENT = "STUDENT"
    SYSTEM = "SYSTEM"
    AI_VLM = "AI_VLM"
    STAFF = "STAFF"
    ADMIN = "ADMIN"

class DepartmentCode(str, Enum):
    FINANCE = "FINANCE"
    ACADEMIC_AFFAIRS = "ACADEMIC_AFFAIRS"
    STUDENT_SERVICES = "STUDENT_SERVICES"
    IT_SUPPORT = "IT_SUPPORT"
