"""Descriptive metadata for the executable NVQS Rule Engine; not a legal database."""

POLICY_REGISTRY = [
    {'id':'POL-NVQS-001','domain':'MILITARY_SERVICE_CONFIRMATION','name':'Identity ownership verification','ruleCode':'RULE_SEC_01_OWNERSHIP_MISMATCH','category':'IDENTITY','trigger':'Authoritative student code or full name is missing or does not exactly match after normalization.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'OWNERSHIP_UNCLEAR','humanAction':'Verify the student identity record.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-002','domain':'MILITARY_SERVICE_CONFIRMATION','name':'Exception request outside workflow','ruleCode':'RULE_POLICY_01_SPECIAL_EXCEPTION_REQUEST','category':'POLICY_SCOPE','trigger':'The request asks for a special exception or outside-workflow handling.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'POLICY_OUT_OF_SCOPE','humanAction':'Handle under the institution exception process.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-003','domain':'MILITARY_SERVICE_CONFIRMATION','name':'Academic authority check','ruleCode':'RULE_AUTH_01_ACADEMIC_STATUS_NEEDS_OFFICER','category':'ACADEMIC','trigger':'Academic status, active term, schedule, or course dates require officer verification.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'AUTHORITY_REQUIRED','humanAction':'Verify authoritative academic facts.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-004','domain':'MILITARY_SERVICE_CONFIRMATION','name':'Temporary address conflict','ruleCode':'RULE_CONFLICT_01_TEMPORARY_ADDRESS_NOT_ALLOWED','category':'ADDRESS','trigger':'Student claim identifies a temporary address.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'DATA_CONFLICT','humanAction':'Request the required permanent-address evidence.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-005','domain':'MILITARY_SERVICE_CONFIRMATION','name':'Required address components','ruleCode':'RULE_FACT_01_INCOMPLETE_ADDRESS','category':'ADDRESS','trigger':'House number, street, ward/commune, or province/city is missing; district is compared when present.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'FACT_UNKNOWN','humanAction':'Request missing address facts.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-006','domain':'MILITARY_SERVICE_CONFIRMATION','name':'Permanent address material conflict','ruleCode':'RULE_CONFLICT_02_PERMANENT_ADDRESS_MISMATCH','category':'ADDRESS','trigger':'Claimed permanent address materially conflicts with the institutional record.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'DATA_CONFLICT','humanAction':'Verify the authoritative address.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-007','domain':'MILITARY_SERVICE_CONFIRMATION','name':'AI provenance and confidence fail-safe','ruleCode':'RULE_FAILSAFE_NON_LIVE_AI','category':'AI_SAFETY','trigger':'AI facts are non-live, fallback, synthetic, missing provenance, or below threshold.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'FACT_UNKNOWN','humanAction':'Perform human review.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-008','domain':'MILITARY_SERVICE_CONFIRMATION','name':'Course date range','ruleCode':'RULE_AUTH_02_COURSE_DATE_INVALID','category':'ACADEMIC','trigger':'Course start/end dates are missing, invalid, or reversed.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'AUTHORITY_REQUIRED','humanAction':'Verify course-date facts.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-009','domain':'MILITARY_SERVICE_CONFIRMATION','name':'Verified permanent address availability','ruleCode':'RULE_FACT_02_MISSING_INSTITUTIONAL_PERMANENT_ADDRESS','category':'ADDRESS','trigger':'The institutional student record has no verified permanent address for comparison.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'FACT_UNKNOWN','humanAction':'Update and verify the student permanent address before processing the request.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-011','domain':'MILITARY_SERVICE_CONFIRMATION','name':'Active SIS registry record','ruleCode':'RULE_AUTH_04_SIS_RECORD_INACTIVE','category':'ACADEMIC','trigger':'The authoritative SIS record is not active.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'AUTHORITY_REQUIRED','humanAction':'Verify the student record status with the institution.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-012','domain':'MILITARY_SERVICE_CONFIRMATION','name':'Current course dates','ruleCode':'RULE_AUTH_03_COURSE_DATE_OUTSIDE_RANGE','category':'ACADEMIC','trigger':'The current date is outside the verified course start/end dates.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'AUTHORITY_REQUIRED','humanAction':'Verify the current enrollment and course dates.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-013','domain':'MILITARY_SERVICE_CONFIRMATION','name':'Authenticated SIS source required','ruleCode':'RULE_FAILSAFE_UNVERIFIED_SIS','category':'AI_SAFETY','trigger':'The student record does not come from an authenticated institutional SIS integration.','systemAction':'ESCALATE_TO_HUMAN','escalationReason':'FACT_UNKNOWN','humanAction':'Verify student facts against the institution data source.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
    {'id':'POL-NVQS-010','domain':'MILITARY_SERVICE_CONFIRMATION','name':'All automatic checks passed','ruleCode':'RULE_AUTO_PASSED_MILITARY_SERVICE_2026','category':'AUTOMATION','trigger':'All identity, academic, address, and AI safety checks pass using live, verified information.','systemAction':'AUTO_APPROVE','escalationReason':None,'humanAction':'No manual review is required unless a later issue is detected.','status':'ACTIVE','sourceType':'INTERNAL_WORKFLOW_POLICY','version':'1.0'},
]
